[package]
name = "sandstorm-vr-setup"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "0.62.2", features = ["Win32_System_Com", "Win32_UI_Shell"] }
dirs = "5.0"
widestring = "0.5"
sysinfo = "0.37"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"


